#!/usr/bin/env python3

# Copyright (c) 2023 by Philip Collier, github.com/AB9IL
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version. There is NO warranty; not even for
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# This updater is for systems WITH Dyatlov Mapmaker running. If you
# have Dyatlov Mapmaker creating your KiwiSDR maps, set the variable
# "current_list" to that file in the mapmaker's directory.

import os
import time

import requests

# minimum time between updates
interval = 7200
# filename of the updater script
updater = "kiwisdr_com-update"
# filename of the KiwiSDR list created by Dyatlov MapMaker
current_list = "kiwisdr_com.js"
# filename of the static receiver list created by the user
static_list = "static_rx.js"
# filename of the unsorted list (cleaned)
stripped_list = "kiwisdr_stripped.py"
# filename of the static receiver list (cleaned)
stripped_static_list = "static_rx.py"
# filename of the sorter script
sorter_scripts = {"kiwisdr_sorter.py", "sdr-stream-bookmarks.py"}

# These paths may be the same or different, depending
# on where you set up your SuperSDR and other users
# of the data.

# path to the kiwidata directory
kiwidata_dir = "/usr/local/src/kiwidata"
# path to the dyatlov directory
dyatlov_dir = "/usr/local/src/dyatlov"

# paths to the lists and sorterscripts
current_path = f"{dyatlov_dir}/{current_list}"
static_path = f"{dyatlov_dir}/{static_list}"
stripped_path = f"{kiwidata_dir}/{stripped_list}"
stripped_static_path = f"{kiwidata_dir}/{stripped_static_list}"
# sorter_path = "/usr/local/src/kiwidata/" + sorter_script
# sdrstreamer_path = "/usr/local/src/kiwidata/" + sdrstreamer_script
# base urls where the list can be downloaded
# url = "http://rx.linkfanel.net/"
# url = "https://rx.skywavelinux.com/"

###############################################################################
#       Edit the variables above; avoid editing the code below
###############################################################################


def read_filtered_lines(file_path):
    with open(file_path, "r") as file:
        for line in file:
            stripped_line = line.strip()
            if (
                stripped_line
                and not stripped_line.startswith("//")
                and not stripped_line.startswith("var")
                and not stripped_line.startswith("[")
                and not stripped_line.startswith("]")
                and not stripped_line.startswith(";")
            ):
                yield line


# age is measured in epoch seconds
try:
    creation_time = os.path.getctime(current_path)
except Exception:
    creation_time = 0

max_age = creation_time + interval
time_now = time.time()

if time_now > max_age:
    print("Downloading a fresh list of KiwiSDRs")
    os.system(f"notify-send 'Downloading a fresh list of KiwiSDRs' &")
    command = f"cd {dyatlov_dir}; ./{updater}"
    os.system(command)

# Process the KiwiSDR list
with open(stripped_path, "w") as out_file:
    out_file.write("dictlist = [\n")
    # Read and filter lines from the source file
    lines = read_filtered_lines(current_path)
    # Write the filtered lines to the destination file
    out_file.writelines(lines)
    out_file.write("]")

# Process the Static receiver list
with open(stripped_static_path, "w") as out_file:
    out_file.write("dictstatic = [\n")
    # Read and filter lines from the source file
    lines = read_filtered_lines(static_path)
    # Write the filtered lines to the destination file
    out_file.writelines(lines)
    out_file.write("]")

# run scripts to use refined sdr data
#
# sdrs sorted by snr and frequency bands
# sorters must be executable and have shebang
for sorter_script in sorter_scripts:
    command = f"cd {kiwidata_dir}; ./{sorter_script}"
    os.system(command)
